name: Publish to Nuget

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Build
      run: msbuild -r /p:Configuration=Release
    
    - name: Publish to NuGet
      run: dotnet nuget push "/home/runner/work/OwlCore.Remoting/OwlCore.Remoting/src/bin/Release/OwlCore.Remoting.*.*.*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
      